const CATALOG = [
    {
        id: 'el1',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/1625/1625099.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el2',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/601/601933.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el3',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909787.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el4',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/590/590685.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el5',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/740/740922.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el6',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/3082/3082025.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el7',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/590/590772.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el8',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/846/846393.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el9',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/3082/3082005.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el10',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909808.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el11',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/3076/3076104.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el12',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/1475/1475906.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el13',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/765/765560.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el14',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4065/4065171.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el15',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/415/415693.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el16',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909899.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el17',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4264/4264610.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el18',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/846/846546.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el19',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2906/2906476.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el20',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909849.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el21',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/5016/5016668.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el22',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4977/4977543.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el23',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/1625/1625099.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el24',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/601/601933.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el25',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909787.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el26',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/590/590685.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el27',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/706/706164.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el28',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/3082/3082025.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el29',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/590/590772.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el30',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/846/846393.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el31',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/3082/3082005.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el32',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909808.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el33',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/3076/3076104.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el34',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/1475/1475906.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el35',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/765/765560.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el36',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4065/4065171.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el37',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/415/415693.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el38',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909899.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el39',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4264/4264610.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el40',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/846/846546.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el41',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/1165/1165363.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el42',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909849.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el43',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/5016/5016668.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el44',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4977/4977543.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el45',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909899.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el46',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4264/4264610.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el47',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/846/846546.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el48',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2906/2906476.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el49',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/2909/2909849.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el50',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/5016/5016668.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
    {
        id: 'el51',
        newSpanOne: 'Новинка',
        newSpanTwo: 'Акция -25%',
        newSpanThree: 'Рекомендуем',
        images: 'https://image.flaticon.com/icons/png/512/4977/4977543.png',
        inStock: 'В наличии',
        code: 4744481010818,
        descr: 'Консервы пастеризованные. Бульон куриный жидкий., 350мл Консервы пастеризованные.',
        price: 500.2,
        oldPrice: 600.2,
    },
];
